object_type: global_settings
overrides:
    "query.factless.useIncidentalFacts": true
    "query.cache.entry.sizeLimit": 10000
    "aggregate.incrementalUpdate.enabled": true
    "connection.groups.testFilesystemTimeout": 20 seconds


  
 
   


