object_type: global_settings
overrides:
    "schema.hintedUserDefinedAggregates.nonFactTables.enabled": false
    "dataloader.operation.timeout": 11 minutes
    "aggregates.create.iris.nojourn.enabled": true
    "bigquery.hll.precision": 15
    "varcharLength.spark": 1
    "thrift.port": 11111
    "statistics.modelvalidation.attributeOrder.maxAcceptableThreshhold": 0.06