object_type: global_settings
overrides:
    "aggregates.create.partition.systemDefinedAggregate.threshold": 50000.0
    "query.factless.useIncidentalFacts": true
    "query.cache.entry.sizeLimit": 10000
 
   


